### ISSUE TITLE
ModuleNotFoundError: No module named 'cosmopit'

### ISSUE THREAD

**Issue by felipeavila331** [lontelis/cosmopit#1]
Hi!

I used the installation command you suggest with pip, but when I call the library I get the following error:

ModuleNotFoundError: No module named 'cosmopit'

any suggestion?

thanks!

**Comment by lontelis** [comment]
Hi Felipe,

Apologise for the late reply, but I was really busy. 
I guess you have correct already your problem. In case, I think you have this problem due to the following reason.
I think you have not installed correctly the cosmopit package, or your not on the same folder as the cosmopit package,
in order to use it. 

A suggestion is to redownload the cosmopit package in a folder, and be in that folder when you import the cosmopit.

Please let me know if you fixed the problem.

Best regards,
Pierros Ntelis

**Comment by felipeavila331** [comment]
Dear Dr. Ntelis,

I would like to express my sincere gratitude for your email and the invaluable suggestion you provided. I followed your advice, re-downloaded the "cosmopit" package, and made sure to be in the correct folder when importing it. I am pleased to inform you that your tip proved to be highly effective, and I successfully resolved the problem. Your expertise and assistance were instrumental in finding a solution, and I greatly appreciate your support. I will close this issue.

Best regards,
Felipe
